apiVersion: hyperspike.io/v1
kind: Valkey
metadata:
  labels:
    app.kubernetes.io/name: valkey-operator
    app.kubernetes.io/managed-by: kustomize
  name: vk2
spec:
  nodes: 3
  volumePermissions: true
  prometheus: false
  tls: true
  certIssuer: selfsigned
  prometheusLabels:
    prometheus: prometheus
  storage:
    spec:
      resources:
        requests:
          storage: 2Gi
      accessModes:
        - ReadWriteOnce
